server:
  port: 8086

spring:
  application:
    name: zmanager
  datasource:
    username: root
    password: root
    url: jdbc:mysql://101.132.128.127:3307/zmanager?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 101.132.128.127
    port: 6379
    lettuce:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: -1
        min-idle: 2
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# jwt
jwt:
  config:
    enabled: true
    key-location: felordcn.jks
    key-alias: felordcn
    key-pass: 123456
    iss: felord.cn
    sub: all
    access-exp-days: 30
    refresh-exp-days: 90